app = "my-sword-bot"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  
  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    method = "get"
    path = "/health"
